version: '3'
services:
  interfaz-grafica:
    build:
      context: ./interfaz  # Ruta de tu proyecto React
    ports:
      - "5173:5173"  # Puerto de la interfaz React
    networks:
      - lab_virtual_net  # 🔵 Red corregida

  rust-server:
    build:
      context: ./qtestapp # Ruta de tu proyecto Rust
    ports:
      - "8080:8080"  # Puerto de la API HTTP
      - "8081:8081"  # Puerto WebSocket
      - "3000:3000"  # Puerto Qemu
    environment:
      - QEMU_URL=0.0.0.0:3000
      - WS_URL=0.0.0.0:8081
    networks:
      - lab_virtual_net  # 🔵 Red corregida

networks:
  lab_virtual_net:  # 🔵 Red corregida
    driver: bridge
